Fixes #15417: rudder-webapp package cannot install, as the webapp exits when the ldap is not initialized

diff --git a/rudder-webapp/debian/postinst b/rudder-webapp/debian/postinst
--- a/rudder-webapp/debian/postinst
+++ b/rudder-webapp/debian/postinst
@@ -135,7 +135,8 @@ case "$1" in
 
   # Restart the webapp
   echo -n "INFO: Restarting Rudder webapp and inventory-endpoint..."
-  service rudder-jetty start >/dev/null 2>&1
+  # this may fails when ldap is not yet initialized
+  service rudder-jetty start >/dev/null 2>&1 || true
   echo " Done"
 
     ;;
