Fixes #18045: When rudder-webapp postinstall fails, everything fails

diff --git a/rudder-webapp/debian/postinst b/rudder-webapp/debian/postinst
--- a/rudder-webapp/debian/postinst
+++ b/rudder-webapp/debian/postinst
@@ -32,7 +32,19 @@ case "$1" in
       # unload ncf-api-virtualenv conf at upgrade
       a2disconf ncf-api-virtualenv >/dev/null 2>&1 || true
       
-      /opt/rudder/share/package-scripts/rudder-webapp-postinst "${RUDDER_FIRST_INSTALL}" "apache2"
+      if ! /opt/rudder/share/package-scripts/rudder-webapp-postinst "${RUDDER_FIRST_INSTALL}" "apache2"
+        echo "**************************************************************************************"
+        echo "ERROR: rudder-webapp postinstall script failed !"
+        echo ""
+        echo "Trying to recover the problem, you should check that your instance is properly working"
+        echo ""
+        echo "   This should not happen, please open an issue for this problem on "
+        echo "         https://issues.rudder.io/projects/rudder/issues/new"
+        echo "**************************************************************************************"
+        LOG_FILE="/var/log/rudder/install/rudder-webapp-fail-$(date +%Y%m%d%H%M%S).log"
+        /opt/rudder/bin/rudder-fix-repository-permissions  >> ${LOG_FILE}
+      fi
+
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
