Refs #3725 - Fix typo on rudder-reports package postinst and reformat rudder-inventory-ldap output

diff --git a/rudder-inventory-ldap/debian/postinst b/rudder-inventory-ldap/debian/postinst
--- a/rudder-inventory-ldap/debian/postinst
+++ b/rudder-inventory-ldap/debian/postinst
@@ -20,7 +20,9 @@ set -e
 
 case "$1" in
     configure)
-		invoke-rc.d rsyslog restart
+		echo -n "INFO: Restarting syslogd..."
+		invoke-rc.d rsyslog restart >/dev/null 2>&1
+		echo " Done"
 
 		RUDDER_SHARE=/opt/rudder/share
 		RUDDER_UPGRADE_TOOLS=${RUDDER_SHARE}/upgrade-tools
@@ -50,13 +52,13 @@ case "$1" in
 			if [ "z${REINIT_DB}" = "zyes" ]; then
 				# Do we have a database backup to restore from?
 				if [ ! -f ${BACKUP_LDIF} ]; then
-					echo >&2 "No database backup for old version. Can't upgrade rudder-inventory-ldap database!"
+					echo >&2 "ERROR: No database backup for old version. Can't upgrade rudder-inventory-ldap database!"
 					exit 1
 				fi
 
 				# Stop OpenLDAP - use forcestop to avoid the init script failing
 				# when trying to do the backup with bad libdb versions
-				echo -n "Stopping slapd..."
+				echo -n "INFO: Stopping slapd..."
 				invoke-rc.d slapd forcestop >/dev/null 2>&1
 				echo " Done"
 
@@ -69,13 +71,13 @@ case "$1" in
 				/opt/rudder/sbin/slapadd -q -l ${BACKUP_LDIF}
 
 				# Start OpenLDAP
-				echo -n "Starting slapd..."
+				echo -n "INFO: Starting slapd..."
 				invoke-rc.d slapd start >/dev/null 2>&1
 				echo " Done"
 
-				echo "OpenLDAP database was successfully upgraded to new format"
-				echo "You can safely remove the backups in ${LDAP_BACKUP_DIR}"
-				echo "and ${BACKUP_LDIF}"
+				echo "INFO: OpenLDAP database was successfully upgraded to new format"
+				echo "INFO: You can safely remove the backups in ${LDAP_BACKUP_DIR}"
+				echo "INFO: and ${BACKUP_LDIF}"
 
 			fi
 		fi
@@ -87,11 +89,11 @@ case "$1" in
 			grep ^index /opt/rudder/etc/openldap/slapd.conf | sed 's/\s\+/\t/g' | cut -f2 | sed 's/,/\n/g' | sort > ${SLAPD_DEFINED_INDEXES}
 			ls  /var/rudder/ldap/openldap-data/*.bdb | xargs -n 1 -I{} basename {} .bdb | sort | egrep -v '^(dn2id|id2entry)' > ${SLAPD_ACTUAL_INDEXES}
 			if ! diff ${SLAPD_DEFINED_INDEXES} ${SLAPD_ACTUAL_INDEXES} > /dev/null; then
-				echo "OpenLDAP indexes are not up to date, reindexing..."
-				invoke-rc.d slapd stop
-				/opt/rudder/sbin/slapindex
-				invoke-rc.d slapd start
-				echo "OpenLDAP indexes updated."
+				echo -n "INFO: OpenLDAP indexes are not up to date, reindexing..."
+				invoke-rc.d slapd stop >/dev/null 2>&1
+				/opt/rudder/sbin/slapindex >/dev/null 2>&1
+				invoke-rc.d slapd start >/dev/null 2>&1
+				echo " Done."
 			fi
 		fi
 		# Remove temporary files about LDAP indexes
