Fixes #21097: Cleanup package build

diff --git a/rudder-server/SOURCES/rudder-upgrade b/rudder-server/SOURCES/rudder-upgrade
--- a/rudder-server/SOURCES/rudder-upgrade
+++ b/rudder-server/SOURCES/rudder-upgrade
@@ -45,11 +45,11 @@ trap 'anomaly_handler ${LINENO}' ERR INT TERM
 # - All versions : Check for the PostgreSQL version
 # - All versions : Create ncf technique update flag and restart at the end of the script
 # - 6.0.0        : Remove ncf hooks
-# - 6.0.4        : Ensure that rudder-slapd sockbuf_max_incoming_auth is not lost at upgrade 
+# - 6.0.4        : Ensure that rudder-slapd sockbuf_max_incoming_auth is not lost at upgrade
 # - 6.1.0        : Migrate RudderUniqueID to the template format
-# - 6.1.0        : Add indexes cn,softwareVersion,directiveId in slapd.conf 
+# - 6.1.0        : Add indexes cn,softwareVersion,directiveId in slapd.conf
 # - 6.1.1        : Update apache conf if it does not contain technique editor conf (file not updated by packaging
-# - 6.2.0        : Remove unused index on RudderSysEvents  
+# - 6.2.0        : Remove unused index on RudderSysEvents
 # - 6.2.0~beta2  : Add software and modifyTimestamp indexes in slapd.conf
 # - 7.0.0~alpha1 : Rename property rudder.community.port into rudder.policy.distribution.port.cfengine
 # - 7.0.0~beta2  : Change the way compliance is computed - change table ReportsExecution
@@ -114,9 +114,8 @@ fi
 
 # Override any server values with those from ${RUDDER_ROLES_FILE}, unless this is a monolithic
 # Rudder server installation (to keep using localhost)
-RUDDER_ROLE_SERVER_ROOT="${RUDDER_OPT}/etc/server-roles.d/rudder-server-root"
 RUDDER_ROLES_FILE="${RUDDER_VAR}/cfengine-community/inputs/rudder-server-roles.conf"
-if [ ! -f ${RUDDER_ROLE_SERVER_ROOT} -a -f ${RUDDER_ROLES_FILE} ]; then
+if [ -f ${RUDDER_ROLES_FILE} ]; then
   ROLE_HOSTNAME=$(grep "^rudder-db:" ${RUDDER_ROLES_FILE} | cut -d: -f2 | cut -d, -f1 | tr -d " ")
   if [ ! -z ${ROLE_HOSTNAME} ]; then
     SQL_SERVER=${ROLE_HOSTNAME}
@@ -225,7 +224,7 @@ remove_system_technique_from_system_directory() {
     rm -rf ${INITTECHDIR}
   fi
 }
- 
+
 # Helper function to compare version numbers with 2 components
 ver() { printf "1%03d%03d" `echo "$1" | tr '.' ' '`; }
 
@@ -309,12 +308,12 @@ upgrade_system_techniques() {
   update_rudder_repository_from_system_directory /opt/rudder/share/techniques/system/server-common/ techniques/system/server-common/
   update_rudder_repository_from_system_directory /opt/rudder/share/techniques/system/common/ techniques/system/common/
   update_rudder_repository_from_system_directory /opt/rudder/share/techniques/system/rudder-service-apache/ techniques/system/rudder-service-apache/
-  update_rudder_repository_from_system_directory /opt/rudder/share/techniques/system/rudder-service-relayd/ techniques/system/rudder-service-relayd/    
+  update_rudder_repository_from_system_directory /opt/rudder/share/techniques/system/rudder-service-relayd/ techniques/system/rudder-service-relayd/
   update_rudder_repository_from_system_directory /opt/rudder/share/techniques/system/rudder-service-webapp/ techniques/system/rudder-service-webapp/
-  
+
   STEP="Remove deprecated system Techniques"
   remove_system_technique_from_system_directory server-roles
-  
+
   remove_system_technique_from_system_directory distributePolicy
 }
 
@@ -325,9 +324,9 @@ upgrade_techniques() {
   /opt/rudder/bin/rudder server upgrade-techniques  --autoupdate-technique-library --during-upgrade
 
   # Migrate RudderUniqueID to the template format
-  NB_RUDDER_UNIQUE_ID=$( (grep -Er --exclude="*.xml"  "[^\&]RudderUniqueID" /var/rudder/configuration-repository/techniques 2>/dev/null || true) | wc -l) 
+  NB_RUDDER_UNIQUE_ID=$( (grep -Er --exclude="*.xml"  "[^\&]RudderUniqueID" /var/rudder/configuration-repository/techniques 2>/dev/null || true) | wc -l)
   if [ ${NB_RUDDER_UNIQUE_ID} -ne 0 ]; then
-    echo -n "INFO: Enforcing that Techniques are using correct format" 
+    echo -n "INFO: Enforcing that Techniques are using correct format"
     find ${CONFIGURATION_REPOSITORY}/techniques -type f \( ! -iname '*.xml' \) -print0 | xargs -0 sed -i "s/\([^&]\|^\)RudderUniqueID\([^&]\|$\)/\1\&RudderUniqueID\&\2/g"
     cd ${CONFIGURATION_REPOSITORY}/techniques && git add . >/dev/null 2>&1
     git commit -m "Upgrade Techniques to template format - automatically done by rudder-upgrade script" >/dev/null 2>&1
@@ -354,7 +353,7 @@ upgrade_ncf() {
     chmod -R o-rwx ${CONFIGURATION_REPOSITORY}/ncf/50_techniques/
   fi
 
-  # All Versions: Touch ncf_update_flag_file jetty will be restarted at the end of the script 
+  # All Versions: Touch ncf_update_flag_file jetty will be restarted at the end of the script
   touch /opt/rudder/etc/force_ncf_technique_update
 
   # Handle the case where we have an existing local method and a common method with the same name
@@ -445,7 +444,7 @@ upgrade_database() {
     ${PSQL} -d ${SQL_DATABASE} -f ${RUDDER_UPGRADE_TOOLS}/dbMigration-6.1-6.2-remove-unused-index-on-ruddersysevents.sql > /dev/null
     echo " Done"
   fi
-  
+
   # - 7.0: Change the way compliance is computed
   RES=$(${PSQL} -t -d ${SQL_DATABASE} -c "select count(oid) from pg_class where lower(relname) = 'reportsexecution_insertionid_idx'")
   if [ $RES -ne 0 ]; then
@@ -469,7 +468,7 @@ upgrade_database() {
     ${PSQL} -d ${SQL_DATABASE} -f ${RUDDER_UPGRADE_TOOLS}/dbMigration-7.0-7.1-serial_to_reportid_change.sql > /dev/null
     echo " Done"
   fi
-  
+
   # Now check the fileFormat in the eventlog
   upgrade_eventlog
 
@@ -548,14 +547,14 @@ upgrade_slapdconf() {
   fi
 
   if ${NEED_REINDEX}; then
-    # stop slapd, slapindex -q, start slapd. 
+    # stop slapd, slapindex -q, start slapd.
     systemctl stop rudder-slapd
     echo -n "Reindexing LDAP directory - this may take a few minutes..."
     su - rudder-slapd -s /bin/sh -c "/opt/rudder/sbin/slapindex"
     echo " Done"
     systemctl start rudder-slapd
   fi
-} 
+}
 
 ################################################################################
 # Check and upgrade plugins
@@ -567,7 +566,7 @@ upgrade_plugins() {
     rudder package update  || true
     rudder package upgrade-all || true
   else
-    echo "Plugins were not updated, because connection test is failing, please upgrade your plugins manually"  
+    echo "Plugins were not updated, because connection test is failing, please upgrade your plugins manually"
   fi
 
   if [ -f $PLUGIN_STATUS_FILE ]; then
